name: Deploy to On-Prem Server

on:
  push:
    branches:
      - main

env:
  CI: false
  MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
  PORT: ${{ secrets.PORT }}
  INTERNAL_SERVER: ${{ secrets.INTERNAL_SERVER }}
  EXPRESS_SERVER: ${{ secrets.REACT_APP_EXPRESS_SERVER }}

jobs:
  build-and-deploy:
    runs-on: self-hosted  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build Frontend
      run: |
        npm run install-client
        npm run build-client
    
    - name: Copy Build Files
      run: echo ${{ secrets.SELF_HOSTED_PW }} | sudo -S cp -r /home/administrator/actions-runner/_work/LHA/LHA/frontend/history-archives/build/ /var/www/html
    
    - name: Copy Server Secrets
      run: echo ${{ secrets.SELF_HOSTED_PW }} | sudo -S cp -r /secrets/.env /home/administrator/actions-runner/_work/LHA/LHA/backend

    - name: Deploy Backend
      run: |
        npm run install-server
        npm run deploy-server
        
          
        
